node {
    stage('Preparation') {
        catchError(buildResult: 'SUCCESS') {
            sh 'docker stop getting-started'
            sh 'docker rm getting-started'
        }
    }
    stage('Build') {
        build 'toDoApp'
    }
    stage('Results') {
        build 'testToDoApp'
    }
}